-- Reserva online v2: agenda recurrente, sesiones de 30/45 minutos y consentimientos.
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.appointment_availability_rules (
  id bigint generated by default as identity primary key,
  iso_weekday smallint not null check (iso_weekday between 1 and 7),
  starts_at time not null,
  ends_at time not null,
  enabled boolean not null default true,
  constraint availability_rule_valid_range check (starts_at < ends_at),
  constraint availability_rule_unique unique (iso_weekday, starts_at, ends_at)
);

alter table public.appointment_availability_rules enable row level security;
revoke all on table public.appointment_availability_rules from anon, authenticated;

insert into public.appointment_availability_rules (iso_weekday, starts_at, ends_at)
values
  (2, '09:00', '13:00'),
  (3, '15:00', '19:00'),
  (4, '09:00', '13:00'),
  (4, '15:00', '19:00'),
  (5, '09:00', '13:00'),
  (5, '15:00', '19:00')
on conflict do nothing;

alter table public.appointment_bookings
  alter column slot_id drop not null,
  add column if not exists starts_at timestamptz,
  add column if not exists ends_at timestamptz,
  add column if not exists duration_minutes smallint,
  add column if not exists price_eur numeric(6,2),
  add column if not exists service_code text,
  add column if not exists cancellation_accepted boolean not null default false,
  add column if not exists informed_consent_accepted boolean not null default false,
  add column if not exists signer_name text,
  add column if not exists privacy_version text,
  add column if not exists consent_version text,
  add column if not exists cancellation_version text,
  add column if not exists accepted_at timestamptz;

-- Conserva posibles reservas creadas con el MVP anterior.
update public.appointment_bookings b
set starts_at = s.starts_at,
    ends_at = s.ends_at,
    duration_minutes = round(extract(epoch from (s.ends_at - s.starts_at)) / 60)::smallint
from public.appointment_slots s
where b.slot_id = s.id
  and b.starts_at is null;

create index if not exists appointment_bookings_time_idx
  on public.appointment_bookings (starts_at, ends_at)
  where status in ('confirmed', 'pending');

create or replace function public.get_available_appointment_starts(
  p_duration_minutes integer,
  p_days integer default 30
)
returns table (starts_at timestamptz, ends_at timestamptz)
language sql
security definer
set search_path = public, pg_temp
stable
as $$
  with params as (
    select
      case when p_duration_minutes in (30, 45) then p_duration_minutes else null end as duration_minutes,
      least(greatest(coalesce(p_days, 30), 1), 60) as days_to_show
  ),
  local_days as (
    select d::date as local_date
    from params p
    cross join generate_series(
      (now() at time zone 'Europe/Madrid')::date,
      (now() at time zone 'Europe/Madrid')::date + (p.days_to_show - 1),
      interval '1 day'
    ) d
    where p.duration_minutes is not null
  ),
  candidates as (
    select
      (g.local_start at time zone 'Europe/Madrid') as candidate_start,
      ((g.local_start + make_interval(mins => p.duration_minutes)) at time zone 'Europe/Madrid') as candidate_end
    from local_days d
    join public.appointment_availability_rules r
      on r.iso_weekday = extract(isodow from d.local_date)::smallint
     and r.enabled
    cross join params p
    cross join lateral generate_series(
      d.local_date + r.starts_at,
      d.local_date + r.ends_at - make_interval(mins => p.duration_minutes),
      interval '15 minutes'
    ) g(local_start)
  )
  select c.candidate_start, c.candidate_end
  from candidates c
  where c.candidate_start >= now() + interval '24 hours'
    and not exists (
      select 1
      from public.appointment_bookings b
      where b.status in ('confirmed', 'pending')
        and b.starts_at is not null
        and tstzrange(b.starts_at, b.ends_at, '[)') && tstzrange(c.candidate_start, c.candidate_end, '[)')
    )
  order by c.candidate_start;
$$;

create or replace function public.create_calendar_booking(
  p_starts_at timestamptz,
  p_duration_minutes integer,
  p_patient_name text,
  p_patient_email text,
  p_patient_phone text,
  p_privacy_acknowledged boolean,
  p_cancellation_accepted boolean,
  p_informed_consent_accepted boolean,
  p_signer_name text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_booking_id uuid;
  v_ends_at timestamptz;
  v_local_start timestamp;
  v_rule_matches boolean;
  v_price numeric(6,2);
  v_service_code text;
begin
  if p_duration_minutes not in (30, 45) then
    raise exception 'Duración no válida';
  end if;

  if p_starts_at < now() + interval '24 hours' then
    raise exception 'La cita debe reservarse con al menos 24 horas de antelación';
  end if;

  if p_starts_at > now() + interval '60 days' then
    raise exception 'La cita solicitada está fuera del periodo de reserva';
  end if;

  if nullif(btrim(p_patient_name), '') is null
     or nullif(btrim(p_signer_name), '') is null then
    raise exception 'Faltan el nombre o la firma';
  end if;

  if nullif(btrim(coalesce(p_patient_email, '')), '') is null
     and nullif(btrim(coalesce(p_patient_phone, '')), '') is null then
    raise exception 'Debe indicarse un canal de contacto';
  end if;

  if not coalesce(p_privacy_acknowledged, false)
     or not coalesce(p_cancellation_accepted, false)
     or not coalesce(p_informed_consent_accepted, false) then
    raise exception 'Deben aceptarse las condiciones y consentimientos';
  end if;

  v_ends_at := p_starts_at + make_interval(mins => p_duration_minutes);
  v_local_start := p_starts_at at time zone 'Europe/Madrid';

  select exists (
    select 1
    from public.appointment_availability_rules r
    where r.enabled
      and r.iso_weekday = extract(isodow from v_local_start)::smallint
      and v_local_start::time >= r.starts_at
      and (v_ends_at at time zone 'Europe/Madrid')::time <= r.ends_at
      and extract(minute from v_local_start)::integer % 15 = 0
      and extract(second from v_local_start) = 0
  ) into v_rule_matches;

  if not v_rule_matches then
    raise exception 'El horario solicitado no pertenece a la agenda disponible';
  end if;

  -- Bloqueo transaccional único para impedir reservas simultáneas solapadas.
  perform pg_advisory_xact_lock(81726354);

  if exists (
    select 1
    from public.appointment_bookings b
    where b.status in ('confirmed', 'pending')
      and b.starts_at is not null
      and tstzrange(b.starts_at, b.ends_at, '[)') && tstzrange(p_starts_at, v_ends_at, '[)')
  ) then
    raise exception 'Ese horario ya no está disponible';
  end if;

  v_price := case p_duration_minutes when 30 then 40.00 else 60.00 end;
  v_service_code := case p_duration_minutes when 30 then 'session_30' else 'session_45' end;

  insert into public.appointment_bookings (
    patient_name, patient_email, patient_phone, status,
    starts_at, ends_at, duration_minutes, price_eur, service_code,
    privacy_accepted, cancellation_accepted, informed_consent_accepted,
    signer_name, privacy_version, consent_version, cancellation_version, accepted_at
  ) values (
    left(btrim(p_patient_name), 120),
    nullif(left(btrim(coalesce(p_patient_email, '')), 254), ''),
    nullif(left(btrim(coalesce(p_patient_phone, '')), 30), ''),
    'confirmed',
    p_starts_at, v_ends_at, p_duration_minutes, v_price, v_service_code,
    true, true, true,
    left(btrim(p_signer_name), 120), '1.1', '1.1', '1.0', now()
  ) returning id into v_booking_id;

  return v_booking_id;
end;
$$;

revoke all on function public.get_available_appointment_starts(integer, integer) from public;
revoke all on function public.create_calendar_booking(timestamptz, integer, text, text, text, boolean, boolean, boolean, text) from public;
grant execute on function public.get_available_appointment_starts(integer, integer) to anon;
grant execute on function public.create_calendar_booking(timestamptz, integer, text, text, text, boolean, boolean, boolean, text) to anon;

-- La tabla de reservas continúa sin lectura ni inserción directa para el público.
revoke all on table public.appointment_bookings from anon;
